[project]
name = "mcp-server-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.14.5",
    "python-dotenv>=1.2.1",
    "temporalio>=1.22.0",
]
